import Foundation

// Extension file for additional prompt categories
extension Name5PromptData {
    // MARK: - Everyday Life (30 prompts)
    static let everydayPrompts: [Name5Prompt] = [
        Name5Prompt(text: "Name 5 things in a bathroom", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things in a kitchen", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 jobs that require a uniform", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 household chores", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 types of doctors", category: .everyday, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 school subjects", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 types of vehicles", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 tools", category: .everyday, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 pieces of furniture", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things you'd find in an office", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 clothing items", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 types of shoes", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things you'd find in a car", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 types of stores", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 emergency services", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things you'd pack for a trip", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things in your wallet or purse", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 rooms in a house", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 apps on your phone", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges],
                   followUpQuestion: "Which one couldn't you live without?"),
        Name5Prompt(text: "Name 5 colors", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 types of weather", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 months of the year", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 days of the week", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 pets people have", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 places in a mall or shopping center", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things you'd see at a park", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 types of jobs or careers", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things that have buttons", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things that use batteries", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things you use every morning", category: .everyday, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges])
    ]

    // MARK: - Abstract & Creative (30 prompts)
    static let abstractPrompts: [Name5Prompt] = [
        Name5Prompt(text: "Name 5 things that are round", category: .abstract, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things that are red", category: .abstract, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things that are soft", category: .abstract, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things that make you happy", category: .abstract, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges],
                   followUpQuestion: "Which one did you experience most recently?"),
        Name5Prompt(text: "Name 5 things that are loud", category: .abstract, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things that are cold", category: .abstract, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things that are hot", category: .abstract, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things you can't live without", category: .abstract, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges],
                   followUpQuestion: "Which one would be hardest to give up?"),
        Name5Prompt(text: "Name 5 things that smell good", category: .abstract, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things that fly", category: .abstract, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things you're grateful for", category: .abstract, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things that are sticky", category: .abstract, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things that are square", category: .abstract, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things that are shiny", category: .abstract, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things that are heavy", category: .abstract, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things that are delicate", category: .abstract, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things you can recycle", category: .abstract, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things that grow", category: .abstract, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things that melt", category: .abstract, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things that bounce", category: .abstract, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things that make noise when you walk", category: .abstract, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things you'd save in a fire", category: .abstract, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges],
                   followUpQuestion: "What's the story behind your #1?"),
        Name5Prompt(text: "Name 5 things that are expensive", category: .abstract, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things that are free", category: .abstract, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things that come in pairs", category: .abstract, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things that are waterproof", category: .abstract, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things that have wheels", category: .abstract, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things you'd bring to a deserted island", category: .abstract, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges],
                   followUpQuestion: "What would you miss most?"),
        Name5Prompt(text: "Name 5 things that make you laugh", category: .abstract, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things you do when you're stressed", category: .abstract, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges])
    ]

    // MARK: - Social & Relationships (25 prompts - exclude from professional)
    static let socialPrompts: [Name5Prompt] = [
        Name5Prompt(text: "Name 5 first date ideas", category: .social, difficulty: .easy,
                   contexts: [.friends, .newPeople], ageGroups: [.teens, .adults]),
        Name5Prompt(text: "Name 5 qualities in a good friend", category: .social, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things you'd tell your younger self", category: .social, difficulty: .medium,
                   contexts: [.friends, .newPeople], ageGroups: [.adults],
                   followUpQuestion: "Which one did you learn the hard way?"),
        Name5Prompt(text: "Name 5 conversation starters", category: .social, difficulty: .medium,
                   contexts: [.friends, .newPeople], ageGroups: [.teens, .adults]),
        Name5Prompt(text: "Name 5 red flags in a relationship", category: .social, difficulty: .medium,
                   contexts: [.friends, .newPeople], ageGroups: [.adults]),
        Name5Prompt(text: "Name 5 icebreaker questions", category: .social, difficulty: .medium,
                   contexts: [.friends, .newPeople], ageGroups: [.teens, .adults]),
        Name5Prompt(text: "Name 5 things couples argue about", category: .social, difficulty: .easy,
                   contexts: [.friends], ageGroups: [.adults]),
        Name5Prompt(text: "Name 5 ways to cheer someone up", category: .social, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 reasons to celebrate", category: .social, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 fun group activities", category: .social, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things that make someone a good listener", category: .social, difficulty: .medium,
                   contexts: [.friends, .newPeople], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 ways to meet new people", category: .social, difficulty: .easy,
                   contexts: [.friends, .newPeople], ageGroups: [.teens, .adults]),
        Name5Prompt(text: "Name 5 party themes", category: .social, difficulty: .easy,
                   contexts: [.friends, .family], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things you should never say on a first date", category: .social, difficulty: .medium,
                   contexts: [.friends], ageGroups: [.adults],
                   followUpQuestion: "Which one have you heard?"),
        Name5Prompt(text: "Name 5 ways to show appreciation", category: .social, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 love languages", category: .social, difficulty: .medium,
                   contexts: [.friends, .newPeople], ageGroups: [.adults]),
        Name5Prompt(text: "Name 5 things friends do together", category: .social, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 reasons to call a friend", category: .social, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 embar rassing moments everyone has", category: .social, difficulty: .medium,
                   contexts: [.friends], ageGroups: [.teens, .adults],
                   followUpQuestion: "Which one happened to you?"),
        Name5Prompt(text: "Name 5 signs someone has a crush", category: .social, difficulty: .easy,
                   contexts: [.friends], ageGroups: [.teens, .adults]),
        Name5Prompt(text: "Name 5 things you should always do before moving in together", category: .social, difficulty: .medium,
                   contexts: [.friends], ageGroups: [.adults]),
        Name5Prompt(text: "Name 5 ways to apologize", category: .social, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 dealbreakers in a friendship", category: .social, difficulty: .medium,
                   contexts: [.friends, .newPeople], ageGroups: [.teens, .adults]),
        Name5Prompt(text: "Name 5 things you can't forget for a sleepover", category: .social, difficulty: .easy,
                   contexts: [.friends, .family], ageGroups: [.kids, .teens]),
        Name5Prompt(text: "Name 5 inside jokes with your friends", category: .social, difficulty: .easy,
                   contexts: [.friends], ageGroups: [.teens, .adults],
                   followUpQuestion: "Tell the story behind one!")
    ]

    // MARK: - Nostalgia & Generations (30 prompts)
    static let nostalgiaPrompts: [Name5Prompt] = [
        Name5Prompt(text: "Name 5 '90s cartoons", category: .nostalgia, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.adults, .allAges],
                   followUpQuestion: "Which one holds up today?"),
        Name5Prompt(text: "Name 5 '80s movies", category: .nostalgia, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 toys from your childhood", category: .nostalgia, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges],
                   followUpQuestion: "Which one do you wish you still had?"),
        Name5Prompt(text: "Name 5 things from your childhood that kids today wouldn't understand", category: .nostalgia, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.adults, .allAges],
                   followUpQuestion: "Which one do you miss most?"),
        Name5Prompt(text: "Name 5 '90s fashion trends", category: .nostalgia, difficulty: .medium,
                   contexts: [.friends, .newPeople], ageGroups: [.adults]),
        Name5Prompt(text: "Name 5 old-school video games", category: .nostalgia, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 songs you loved in high school", category: .nostalgia, difficulty: .easy,
                   contexts: [.friends, .newPeople], ageGroups: [.adults],
                   followUpQuestion: "Which one still gets you hyped?"),
        Name5Prompt(text: "Name 5 discontinued snacks you miss", category: .nostalgia, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 '2000s pop stars", category: .nostalgia, difficulty: .medium,
                   contexts: [.friends, .newPeople], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 TV channels you watched as a kid", category: .nostalgia, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 playground games", category: .nostalgia, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 obsolete technologies", category: .nostalgia, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.adults, .allAges],
                   followUpQuestion: "Which one do you remember using?"),
        Name5Prompt(text: "Name 5 childhood snacks", category: .nostalgia, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 Saturday morning cartoons", category: .nostalgia, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 classic Nickelodeon shows", category: .nostalgia, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 boy bands or girl groups", category: .nostalgia, difficulty: .easy,
                   contexts: [.friends, .newPeople], ageGroups: [.adults]),
        Name5Prompt(text: "Name 5 things you did before smartphones", category: .nostalgia, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 flip phones or old cell phone brands", category: .nostalgia, difficulty: .medium,
                   contexts: [.friends, .newPeople], ageGroups: [.adults]),
        Name5Prompt(text: "Name 5 '90s sitcoms", category: .nostalgia, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 Disney Channel original movies", category: .nostalgia, difficulty: .hard,
                   contexts: [.friends, .newPeople], ageGroups: [.adults]),
        Name5Prompt(text: "Name 5 things you used to do at recess", category: .nostalgia, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 candies from a candy store", category: .nostalgia, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 classic arcade games from the '80s or '90s", category: .nostalgia, difficulty: .hard,
                   contexts: [.friends, .newPeople], ageGroups: [.adults]),
        Name5Prompt(text: "Name 5 things you learned in elementary school", category: .nostalgia, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 childhood Halloween costumes you remember", category: .nostalgia, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things from a '90s bedroom", category: .nostalgia, difficulty: .medium,
                   contexts: [.friends, .newPeople], ageGroups: [.adults]),
        Name5Prompt(text: "Name 5 old internet trends or websites", category: .nostalgia, difficulty: .medium,
                   contexts: [.friends, .newPeople], ageGroups: [.adults],
                   followUpQuestion: "What was your first social media?"),
        Name5Prompt(text: "Name 5 cassette or VHS memories", category: .nostalgia, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.adults]),
        Name5Prompt(text: "Name 5 things you collected as a kid", category: .nostalgia, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges],
                   followUpQuestion: "Do you still have any?"),
        Name5Prompt(text: "Name 5 classic kids' books", category: .nostalgia, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges])
    ]
}
