import Foundation

struct Name5PromptData {
    static let allPrompts: [Name5Prompt] = entertainmentPrompts +
                                            foodPrompts +
                                            geographyPrompts +
                                            sportsPrompts +
                                            sciencePrompts +
                                            historyPrompts +
                                            everydayPrompts +
                                            abstractPrompts +
                                            socialPrompts +
                                            nostalgiaPrompts

    // MARK: - Entertainment & Pop Culture (40 prompts)
    private static let entertainmentPrompts: [Name5Prompt] = [
        Name5Prompt(text: "Name 5 Disney movies", category: .entertainment, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges],
                   followUpQuestion: "Which one could you watch over and over?"),
        Name5Prompt(text: "Name 5 Disney villains", category: .entertainment, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges],
                   followUpQuestion: "Who's the most misunderstood?"),
        Name5Prompt(text: "Name 5 superheroes", category: .entertainment, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 Marvel movies", category: .entertainment, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 songs with a color in the title", category: .entertainment, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges],
                   followUpQuestion: "Which one is stuck in your head now?"),
        Name5Prompt(text: "Name 5 Beatles songs", category: .entertainment, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 musical instruments", category: .entertainment, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 reality TV shows", category: .entertainment, difficulty: .medium,
                   contexts: [.friends, .newPeople], ageGroups: [.teens, .adults]),
        Name5Prompt(text: "Name 5 Taylor Swift songs", category: .entertainment, difficulty: .medium,
                   contexts: [.friends, .newPeople], ageGroups: [.teens, .adults, .allAges],
                   followUpQuestion: "What's your Taylor Swift era?"),
        Name5Prompt(text: "Name 5 streaming services", category: .entertainment, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 video game franchises", category: .entertainment, difficulty: .medium,
                   contexts: [.friends, .newPeople], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 Harry Potter characters", category: .entertainment, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges],
                   followUpQuestion: "Which house would you be sorted into?"),
        Name5Prompt(text: "Name 5 Broadway musicals", category: .entertainment, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 famous bands from the 80s", category: .entertainment, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 Pixar movies", category: .entertainment, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges],
                   followUpQuestion: "Which one made you cry?"),
        Name5Prompt(text: "Name 5 TV shows from your childhood", category: .entertainment, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 famous actors/actresses", category: .entertainment, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 classic arcade games", category: .entertainment, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 book series", category: .entertainment, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 famous movie quotes", category: .entertainment, difficulty: .hard,
                   contexts: [.friends, .newPeople], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 podcast genres", category: .entertainment, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 award shows", category: .entertainment, difficulty: .medium,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 dance styles", category: .entertainment, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 famous painters", category: .entertainment, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 genres of music", category: .entertainment, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 cartoon characters", category: .entertainment, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 sitcoms", category: .entertainment, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges],
                   followUpQuestion: "Which one would you want to live in?"),
        Name5Prompt(text: "Name 5 scary movies", category: .entertainment, difficulty: .medium,
                   contexts: [.friends, .newPeople], ageGroups: [.teens, .adults]),
        Name5Prompt(text: "Name 5 Christmas movies", category: .entertainment, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 movie directors", category: .entertainment, difficulty: .hard,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 famous YouTubers or streamers", category: .entertainment, difficulty: .medium,
                   contexts: [.friends, .newPeople], ageGroups: [.kids, .teens, .adults]),
        Name5Prompt(text: "Name 5 animated movies (non-Disney)", category: .entertainment, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 action movie stars", category: .entertainment, difficulty: .medium,
                   contexts: [.friends, .newPeople], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 types of movies", category: .entertainment, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 famous comedians", category: .entertainment, difficulty: .medium,
                   contexts: [.friends, .newPeople], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 Star Wars characters", category: .entertainment, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 board games", category: .entertainment, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges],
                   followUpQuestion: "Which one always causes arguments?"),
        Name5Prompt(text: "Name 5 card games", category: .entertainment, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 music awards", category: .entertainment, difficulty: .medium,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 famous rappers", category: .entertainment, difficulty: .medium,
                   contexts: [.friends, .newPeople], ageGroups: [.teens, .adults, .allAges])
    ]

    // MARK: - Food & Drink (35 prompts)
    private static let foodPrompts: [Name5Prompt] = [
        Name5Prompt(text: "Name 5 pizza toppings", category: .food, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges],
                   followUpQuestion: "What's your most controversial pizza opinion?"),
        Name5Prompt(text: "Name 5 ice cream flavors", category: .food, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 breakfast cereals", category: .food, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 fruits", category: .food, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 vegetables", category: .food, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 fast food restaurants", category: .food, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 types of pasta", category: .food, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 types of cheese", category: .food, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 sandwich types", category: .food, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 coffee drinks", category: .food, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 desserts", category: .food, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 types of cuisine", category: .food, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 potato dishes", category: .food, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 Mexican foods", category: .food, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 Italian dishes", category: .food, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 herbs or spices", category: .food, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 candy bars", category: .food, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 beverages (non-alcoholic)", category: .food, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 types of bread", category: .food, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 breakfast foods", category: .food, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 foods that are green", category: .food, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 BBQ foods", category: .food, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 Asian dishes", category: .food, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 condiments", category: .food, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 types of salad", category: .food, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 soup types", category: .food, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 chocolate brands", category: .food, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 nuts", category: .food, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 seafood types", category: .food, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 berries", category: .food, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 citrus fruits", category: .food, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 types of eggs dishes", category: .food, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 pie flavors", category: .food, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 chip flavors", category: .food, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 food trucks you might see", category: .food, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges])
    ]

    // MARK: - Geography & Travel (35 prompts)
    private static let geographyPrompts: [Name5Prompt] = [
        Name5Prompt(text: "Name 5 U.S. states", category: .geography, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 countries in Europe", category: .geography, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 countries in South America", category: .geography, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 countries in Africa", category: .geography, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 countries in Asia", category: .geography, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 world capitals", category: .geography, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 famous landmarks", category: .geography, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 major cities", category: .geography, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 oceans or seas", category: .geography, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 mountain ranges", category: .geography, difficulty: .hard,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 islands", category: .geography, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 famous bridges", category: .geography, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 languages spoken around the world", category: .geography, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 deserts", category: .geography, difficulty: .hard,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 rivers", category: .geography, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 U.S. state capitals", category: .geography, difficulty: .hard,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 places you'd love to visit", category: .geography, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges],
                   followUpQuestion: "What's #1 on your bucket list?"),
        Name5Prompt(text: "Name 5 continents", category: .geography, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 countries that border France", category: .geography, difficulty: .hard,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 famous waterfalls", category: .geography, difficulty: .hard,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 types of landforms", category: .geography, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 national parks", category: .geography, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 beach destinations", category: .geography, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 cities in California", category: .geography, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 cities in Texas", category: .geography, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 Caribbean countries or islands", category: .geography, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 countries in the Middle East", category: .geography, difficulty: .medium,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 famous museums", category: .geography, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 famous castles or palaces", category: .geography, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 time zones", category: .geography, difficulty: .hard,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 major airports (by code or city)", category: .geography, difficulty: .medium,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 countries that start with 'S'", category: .geography, difficulty: .hard,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 famous streets or avenues", category: .geography, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 Great Lakes", category: .geography, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 currencies used around the world", category: .geography, difficulty: .medium,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges])
    ]

    // MARK: - Sports & Activities (30 prompts)
    private static let sportsPrompts: [Name5Prompt] = [
        Name5Prompt(text: "Name 5 Olympic sports", category: .sports, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 NBA teams", category: .sports, difficulty: .medium,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 NFL teams", category: .sports, difficulty: .medium,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 soccer/football clubs", category: .sports, difficulty: .medium,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 famous athletes", category: .sports, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 pieces of sports equipment", category: .sports, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 water sports", category: .sports, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 winter sports", category: .sports, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things you need for camping", category: .sports, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 hobbies", category: .sports, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 MLB teams", category: .sports, difficulty: .medium,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 NHL teams", category: .sports, difficulty: .medium,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 martial arts", category: .sports, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 racquet sports", category: .sports, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 things to do at a beach", category: .sports, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 famous golf courses or tournaments", category: .sports, difficulty: .hard,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 positions in soccer", category: .sports, difficulty: .medium,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 positions in baseball", category: .sports, difficulty: .medium,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 extreme sports", category: .sports, difficulty: .medium,
                   contexts: [.friends, .newPeople], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 track and field events", category: .sports, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 famous stadiums or arenas", category: .sports, difficulty: .medium,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 types of racing", category: .sports, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 gymnastics events", category: .sports, difficulty: .hard,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 college sports teams", category: .sports, difficulty: .medium,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 things you'd find at a gym", category: .sports, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 famous tennis players", category: .sports, difficulty: .medium,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 Olympic host cities", category: .sports, difficulty: .hard,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 types of swimming strokes", category: .sports, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 team sports", category: .sports, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 individual sports", category: .sports, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges])
    ]

    // MARK: - Science & Nature (35 prompts)
    private static let sciencePrompts: [Name5Prompt] = [
        Name5Prompt(text: "Name 5 planets in our solar system", category: .science, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 mammals that live in the ocean", category: .science, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 types of dinosaurs", category: .science, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 parts of the human body", category: .science, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 birds", category: .science, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 insects", category: .science, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 reptiles", category: .science, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 types of trees", category: .science, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 types of flowers", category: .science, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 natural disasters", category: .science, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 weather phenomena", category: .science, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 chemical elements", category: .science, difficulty: .medium,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 famous scientists or inventors", category: .science, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 constellations", category: .science, difficulty: .hard,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 big cats", category: .science, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 animals that hibernate", category: .science, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 endangered species", category: .science, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 venomous animals", category: .science, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 nocturnal animals", category: .science, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 farm animals", category: .science, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 organs in the human body", category: .science, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 bones in the human body", category: .science, difficulty: .hard,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 types of clouds", category: .science, difficulty: .hard,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 gemstones or minerals", category: .science, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 types of energy", category: .science, difficulty: .medium,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 renewable resources", category: .science, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 ecosystems or biomes", category: .science, difficulty: .hard,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 animals found in the rainforest", category: .science, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 animals found in the Arctic", category: .science, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 types of fish", category: .science, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 animals with stripes or spots", category: .science, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 baby animal names", category: .science, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople], ageGroups: [.kids, .teens, .adults, .allAges],
                   followUpQuestion: "Which baby animal is the cutest?"),
        Name5Prompt(text: "Name 5 animals that lay eggs", category: .science, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 types of sharks", category: .science, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 primate species", category: .science, difficulty: .hard,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges])
    ]

    // MARK: - History & Culture (30 prompts)
    private static let historyPrompts: [Name5Prompt] = [
        Name5Prompt(text: "Name 5 U.S. presidents", category: .history, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 ancient civilizations", category: .history, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 world religions", category: .history, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 U.S. holidays", category: .history, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 famous battles", category: .history, difficulty: .hard,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 world leaders (past or present)", category: .history, difficulty: .medium,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 ancient wonders", category: .history, difficulty: .hard,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 founding fathers", category: .history, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 famous explorers", category: .history, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 wars in history", category: .history, difficulty: .medium,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 monarchs or royalty", category: .history, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 inventions that changed the world", category: .history, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 civil rights leaders", category: .history, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 mythological gods or goddesses", category: .history, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 famous philosophers", category: .history, difficulty: .hard,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 amendments to the U.S. Constitution", category: .history, difficulty: .hard,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 cultural traditions or customs", category: .history, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 historical documents", category: .history, difficulty: .hard,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 medieval jobs or roles", category: .history, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 famous speeches", category: .history, difficulty: .hard,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 decades in the 1900s", category: .history, difficulty: .easy,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 Revolutionary War figures", category: .history, difficulty: .hard,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 famous authors from history", category: .history, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 Native American tribes", category: .history, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 Renaissance artists", category: .history, difficulty: .hard,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 famous queens", category: .history, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 empires throughout history", category: .history, difficulty: .hard,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges]),
        Name5Prompt(text: "Name 5 symbols of different countries", category: .history, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.kids, .teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 famous female historical figures", category: .history, difficulty: .medium,
                   contexts: [.friends, .family, .newPeople, .professional], ageGroups: [.teens, .adults, .allAges]),
        Name5Prompt(text: "Name 5 space missions or programs", category: .history, difficulty: .hard,
                   contexts: [.friends, .newPeople, .professional], ageGroups: [.adults, .allAges])
    ]

    // Due to length, continuing with remaining categories...
}
